name: Makefile CI

on:
  push:
    branches: [ "base" ]
  pull_request:
    branches: [ "base" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install neofetch
      run: sudo apt install -y neofetch
    - name: run neofetch
      run: neofetch --stdout
