name: Makefile CI

on:
  push:
    branches: [ "base" ]
  pull_request:
    branches: [ "base" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Tools and Libraries
      run: sudo apt install -y bison build-essential curl flex git gnat imagemagick libncurses5-dev m4 nasm python-is-python3 uuid-dev zlib1g-dev libssl-dev
    - name: CD into coreboot-GS
      run: cd coreboot-GS
    - name: configure dependencies
      run: git submodule update --init --checkout --recursive

    - name: Install dependencies
      run: make crossgcc-i386 CPUS=$(nproc)

    - name: Building Firmware
      run: ./build-uefi.sh stout
